import json
import logging
from deepdiff import DeepDiff

logger = logging.getLogger(__name__)

def generate_changelog(v1_memo: dict, v2_memo: dict, patch: dict) -> tuple:
    account_id = v2_memo.get("account_id")
    company = v2_memo.get("company_name", "Unknown Company")
    v1_time = v1_memo.get("created_at", "Unknown")
    v2_time = v2_memo.get("created_at", "Unknown")
    
    diff = DeepDiff(v1_memo, v2_memo, ignore_order=True, view='tree')
    
    changes = []
    
    for item in diff.get("dictionary_item_added", []):
        field_path = item.path(output_format='list')
        field_str = "['" + "']['".join(str(k) for k in field_path) + "']"
        changes.append({
            "field": field_str,
            "type": "added",
            "old_value": None,
            "new_value": item.t2,
            "reason": "New field added during onboarding"
        })
        
    for item in diff.get("values_changed", []):
        field_path = item.path(output_format='list')
        field_str = "['" + "']['".join(str(k) for k in field_path) + "']"
        changes.append({
            "field": field_str,
            "type": "updated",
            "old_value": item.t1,
            "new_value": item.t2,
            "reason": "Updated during onboarding"
        })

    for item in diff.get("type_changes", []):
        field_path = item.path(output_format='list')
        field_str = "['" + "']['".join(str(k) for k in field_path) + "']"
        changes.append({
            "field": field_str,
            "type": "updated",
            "old_value": item.t1,
            "new_value": item.t2,
            "reason": "Updated during onboarding (type changed)"
        })
        
    for item in diff.get("iterable_item_added", []):
        field_path = item.path(output_format='list')
        field_str = "['" + "']['".join(str(k) for k in field_path) + "']"
        changes.append({
            "field": field_str,
            "type": "added",
            "old_value": None,
            "new_value": item.t2,
            "reason": "New list item added during onboarding"
        })

    for q in patch.get("resolved_unknowns", []):
        changes.append({
            "field": q,
            "type": "resolved",
            "old_value": "unknown",
            "new_value": "resolved",
            "reason": "Clarified during onboarding call"
        })
        
    total_updated = len([c for c in changes if c["type"] == "updated"])
    total_added = len([c for c in changes if c["type"] == "added"])
    total_resolved = len([c for c in changes if c["type"] == "resolved"])
    remaining = v2_memo.get("questions_or_unknowns", [])
    
    changes_json = {
        "account_id": account_id,
        "company_name": company,
        "v1_created_at": v1_time,
        "v2_created_at": v2_time,
        "total_fields_changed": total_updated,
        "total_fields_added": total_added,
        "total_fields_resolved": total_resolved,
        "total_remaining_unknowns": len(remaining),
        "changes": changes,
        "remaining_unknowns": remaining
    }
    
    # Build MD
    md_lines = [
        f"# Changelog: {company}",
        "",
        f"**Account ID:** {account_id}",
        f"**v1 Created:** {v1_time}",
        f"**v2 Created:** {v2_time}",
        "**Generated By:** Clara AI Pipeline B",
        "",
        "---",
        "",
        "## Summary",
        f"{total_updated} fields updated · {total_added} new fields confirmed · {total_resolved} unknowns resolved · {len(remaining)} unknowns remaining",
        "",
        "---",
        "",
        "## Updated Fields",
        "",
        "| Field | v1 Value | v2 Value | Reason |",
        "|---|---|---|---|"
    ]
    for c in changes:
        if c["type"] == "updated":
            md_lines.append(f"| `{c['field']}` | `{c['old_value']}` | `{c['new_value']}` | {c['reason']} |")
            
    md_lines.extend(["", "---", "", "## New Fields Added"])
    for c in changes:
        if c["type"] == "added":
            md_lines.append(f"- **`{c['field']}`**: `{c['new_value']}` — {c['reason']}")
            
    md_lines.extend(["", "---", "", "## Resolved Unknowns"])
    for c in changes:
        if c["type"] == "resolved":
            md_lines.append(f"- ~~\"{c['field']}\"~~ → Confirmed: {c['reason']}")
            
    md_lines.extend(["", "---", "", "## Remaining Unknowns"])
    if remaining:
        for r in remaining:
            md_lines.append(f"- {r}")
    else:
        md_lines.append("- None")
        
    changes_md = "\n".join(md_lines)
    
    return changes_json, changes_md
